### ISSUE TITLE
Instructions do not lead to a working client

### ISSUE THREAD

**Issue by MatthewBooth** [tebru/retrofit-php-bundle#13]
Guessing this is not compatible with Symfony 3.2 as all I get from the instructions is:

```text
ClassNotFoundException in RestAdapter.php line 110:
Attempted to load class "GoogleTokenAdapter" from namespace "Tebru\Retrofit\Generated\OAuthBundle\RestAdapter".
Did you forget a "use" statement for another namespace?
```

I'm familiar with the square.io RetroFit for Java (and Android) and figured I'd use this for a PHP project I'm working on, but I can't get past the setup instructions.

Here's my services.yml

```yml
parameters:
    # Adapters
    o_auth.google_token.adapter.class: OAuthBundle\RestAdapter\GoogleTokenAdapter

    # Providers
    o_auth.google_token.provider.class: OAuthBundle\RestAdapter\GoogleTokenProvider

    # Services
    o_auth.google_credentials.class: OAuthBundle\Service\GoogleCredentialsService
services:
    # Services
    o_auth.google_credentials.service:
        class: '%o_auth.google_credentials.class%'
        arguments: ['%google.client_id%', '%google.client_secret%', '@foo_service']

    foobar_rest_adapter:
        class: '%tebru_retrofit.rest_adapter.class%'
        factory: ['OAuthBundle\RestAdapter\GoogleTokenProvider', 'get']

    foo_service:
        class: '%o_auth.google_token.adapter.class%'
        factory: ['@foobar_rest_adapter', 'create']
        arguments: ['%o_auth.google_token.adapter.class%']
        tags:
            - { name: tebru_retrofit.register }
```

Or, at least there are the parts that matter.

GoogleTokenAdapter:

```php
interface GoogleTokenAdapter
{
    const BASE_URL = "https://accounts.google.com";

    /**
     * @Rest\GET("/o/oauth2/token")
     * @Rest\QueryMap("params")
     *
     * @param array $params
     *
     * @return
     */
    public function getToken(array $params);
}
```

GoogleTokenProvider:

```php
class GoogleTokenProvider
{
    /**
     * Gets a RetroFit Adapter for Google oAuth Token Access
     *
     * @return RestAdapter
     */
    public function get()
    {
        return RestAdapter::builder()
            ->setBaseUrl(GoogleTokenAdapter::BASE_URL)
            ->build();
    }
}
```

GoogleCredentialsService constructor:

```php
/**
     * GoogleCredentialsService constructor.
     *
     * @param string              $clientId
     * @param string              $clientSecret
     * @param GoogleTokenAdapter $tokenProvider
     */
    public function __construct(string $clientId, string $clientSecret, GoogleTokenAdapter $tokenProvider)
    {
        $this->client = new Client();
        $this->clientId = $clientId;
        $this->clientSecret = $clientSecret;
        $this->tokenProvider = $tokenProvider;
    }
```

**Comment by natebrunette** [comment]
Hi Matt, have you run a cache clear to generate the client yet?  Does the class exist at that path?

**Comment by MatthewBooth** [comment]
@natebrunette 

I've tried without the bundle with the standalone retrofi-php library using the command. It generates the retrofit classes to the cache folder but they are not usable and aren't picked up when running the code, still resulting the error above :(

**Comment by natebrunette** [comment]
Using the bundle, they should be in an environment directory (e.g. dev).  I'm trying to reproduce on a fresh symfony 3.2 install.

**Comment by natebrunette** [comment]
This is working for me.

I'm just using AppBundle, and make a few other small changes to make testing quicker, but otherwise it should be the same.  I ran a composer install and a cache clear, both completed without errors.

```
<?php

namespace AppBundle\RestAdapter;

use Tebru\Retrofit\Annotation\GET;
use Tebru\Retrofit\Annotation\QueryMap;

interface GoogleTokenAdapter
{
    const BASE_URL = 'https://accounts.google.com';

    /**
     * @GET("/o/oauth2/token")
     * @QueryMap("params")
     */
    public function getToken(array $params);
}
```

```
<?php

namespace AppBundle\RestAdapter;

use Tebru\Retrofit\Adapter\Rest\RestAdapter;

class GoogleTokenProvider
{
    public function get()
    {
        return RestAdapter::builder()
            ->setBaseUrl(GoogleTokenAdapter::BASE_URL)
            ->build();
    }
}
```

```
services:
    foobar_rest_adapter:
        class: '%tebru_retrofit.rest_adapter.class%'
        factory: ['AppBundle\RestAdapter\GoogleTokenProvider', 'get']

    foo_service:
        class: 'AppBundle\RestAdapter\GoogleTokenAdapter'
        factory: ['@foobar_rest_adapter', 'create']
        arguments: ['AppBundle\RestAdapter\GoogleTokenAdapter']
        tags:
            - { name: tebru_retrofit.register }
```

I'm making this call in a controller

```
$this->get('foo_service')->getToken([]);
```

This is the generated class

```
<?php

namespace Tebru\Retrofit\Generated\AppBundle\RestAdapter;

class GoogleTokenAdapter implements \AppBundle\RestAdapter\GoogleTokenAdapter
{
    private $baseUrl = null;
    private $client = null;
    private $serializer = null;
    private $eventDispatcher = null;
    public function __construct($baseUrl, \Tebru\Retrofit\Adapter\HttpClientAdapter $client, \JMS\Serializer\Serializer $serializer, \Symfony\Component\EventDispatcher\EventDispatcherInterface $eventDispatcher)
    {
        $this->baseUrl = $baseUrl;
        $this->client = $client;
        $this->serializer = $serializer;
        $this->eventDispatcher = $eventDispatcher;
    }
    public function getToken(array $params)
    {
        $queryArray = \Tebru\Retrofit\Generation\Manipulator\QueryManipulator::boolToString($params);
        $queryString = http_build_query($queryArray);
        $requestUrl = $this->baseUrl . '/o/oauth2/token?' . $queryString;
        $headers = array('Content-Type' => 'application/x-www-form-urlencoded');
        $body = null;
        $request = new \GuzzleHttp\Psr7\Request('GET', $requestUrl, $headers, $body);
        $beforeSendEvent = new \Tebru\Retrofit\Event\BeforeSendEvent($request);
        $this->eventDispatcher->dispatch('retrofit.beforeSend', $beforeSendEvent);
        $request = $beforeSendEvent->getRequest();
        try {
            $response = $this->client->send($request);
        } catch (\Exception $exception) {
            $apiExceptionEvent = new \Tebru\Retrofit\Event\ApiExceptionEvent($exception, $request);
            $this->eventDispatcher->dispatch('retrofit.apiException', $apiExceptionEvent);
            $exception = $apiExceptionEvent->getException();
            throw new \Tebru\Retrofit\Exception\RetrofitApiException(get_class($this), $exception->getMessage(), $exception->getCode(), $exception);
        }
        $afterSendEvent = new \Tebru\Retrofit\Event\AfterSendEvent($request, $response);
        $this->eventDispatcher->dispatch('retrofit.afterSend', $afterSendEvent);
        $response = $afterSendEvent->getResponse();
        $retrofitResponse = new \Tebru\Retrofit\Http\Response($response, 'array', $this->serializer, array());
        $return = $retrofitResponse->body();
        $returnEvent = new \Tebru\Retrofit\Event\ReturnEvent($return);
        $this->eventDispatcher->dispatch('retrofit.return', $returnEvent);
        return $returnEvent->getReturn();
    }
}
```

Available at `var/cache/dev/retrofit/AppBundle/RestAdapter/GoogleTokenAdapter.php`
